### ISSUE TITLE
[Feature] Add consolidated notification for volume or brightness change.

### ISSUE THREAD

**Issue by SherLock707** [ErikReider/SwayNotificationCenter#360] opened 2023-12-25 03:36 UTC
**Current behavior.**
The current behavior of Swaync notification center triggers multiple notifications for each volume or brightness change event. This can be distracting and clutters the user interface.

![image](https://github.com/ErikReider/SwayNotificationCenter/assets/26952545/bc0ea87d-759b-4427-bf7b-00bf0e52f648)

**Solution I'd like**
 I propose implementing a feature that consolidates these notifications into a single popup when either the volume or brightness is adjusted.

**Additional context**
Like how Dunst or Mako does it right now. This is the only thing preventing me from switching to swaync.

**Comment by ErikReider** [comment] 2023-12-25 09:29
Duplicate of #86

This can be done in multiple ways, by replacing the notification manually or by doing this instead https://github.com/ErikReider/SwayNotificationCenter/issues/86#issuecomment-1039825733

Hope this helps :D

**Closed by ErikReider** 2023-12-25 09:29 UTC

**Comment by SherLock707** [comment] 2023-12-25 10:41
Thanks! got it.

![image](https://github.com/ErikReider/SwayNotificationCenter/assets/26952545/30a4ea0c-d981-4bfa-8c76-59064e71e8a3)

**Comment by SherLock707** [comment] 2023-12-25 11:00
@ErikReider , Is there a way I can exclude these volume notification from notification centre?

**Comment by ErikReider** [comment] 2023-12-25 11:19
> @ErikReider , Is there a way I can exclude these volume notification from notification centre?

I'm currently not home for the holidays so I can't check but there should be a flag in notify-send. -t or something if my memory serves me right :)

**Comment by SherLock707** [comment] 2023-12-25 11:25
Thanks for responding!
`-e, --transient  : Create a transient notification`

Happy holidays!
