### ISSUE TITLE
mpris_player times out when waiting for a response from mpd-mpris

### ISSUE THREAD

**Issue by gg-rewrite** [ErikReider/SwayNotificationCenter#241] opened 2023-04-05 14:05 UTC
The main error is `(swaync:21660): ERROR **: 16:49:03.937: mpris_player.vala:101: PlayPause Error: Timeout was reached`.

Other mpris control software (such as playerctl and kdeconnect) don't have any issues with it and controlling other mpris applications (e.g. browsers) works fine. 

The bigger problem is the whole swaync application is unresponsive during the wait plus grabs keyboard input preventing from closing it. 

The possible intermediate solution would be to shorten the timeout and assume the command went through to the mpris client.

**Comment by ErikReider** [comment] 2023-04-05 15:38
What software are you trying to control?

**Comment by gg-rewrite** [comment] 2023-04-06 07:58
Mpd via mpd-mpris

**Comment by fishman** [comment] 2023-05-02 02:55
This issue occurs with https://github.com/eonpatapon/mpDris2

It can be fixed by using https://github.com/szclsya/mpdris2-rs instead

I think the issue itself should be addressed regardless. Since it means that some mpris implementations may cause swaync to segfault

**Comment by ErikReider** [comment] 2023-05-03 14:03
Could you provide a step by step guide of how to reproduce?

**Comment by ErikReider** [comment] 2023-05-04 17:57
Seems like mpDris2 isn't handling the Dbus methods correctly? I'm getting `GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Method "PlayPause" with signature "" on interface "org.mpris.MediaPlayer2.Player" doesn't exist` when trying to execute any method in D-spy

**Comment by ErikReider** [comment] 2023-05-04 18:47
Seems like mpDris2 isn't handling their Dbus interface ideally... Found the issue + other issues caused by this...

**Comment by ErikReider** [comment] 2023-05-04 18:52
Does #253 fix your issues?

**Closed** 2023-05-11 19:19 UTC
Labels: bug
