### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by sachinchaudhary1808** [ErikReider/SwayNotificationCenter#456] opened 2024-07-28 13:21 UTC
**Describe the bug**
when i play a video or music on youtube or something, genrelly the mpris module shows the 2 music windows of the same thing

**To Reproduce**
1. Go 'youtube.com and play a video'
2. run  ' swaync-client -op'
3. See 2 mpris windows 

**Expected behavior**
just want to show only one windows or instance of mpris

**Please provide logs if you're experiencing notification errors / bugs**
[logs](https://pastebin.com/ma2R5C5v)

**Screenshots**
a video here 
https://github.com/ErikReider/SwayNotificationCenter/issues/454#issuecomment-2241718773

**Desktop (please complete the following information):**
 - OS: [nixos-24.05]

**Comment by ErikReider** [comment] 2024-07-28 13:22
Duplicate of #454

**Closed by ErikReider** 2024-07-28 13:22 UTC
Labels: bug
