### ISSUE TITLE
Light theme issue

### ISSUE THREAD

**Issue by kushraj** [ErikReider/SwayNotificationCenter#2] opened 2021-07-29 06:04 UTC
nice work, this looks quite usable even in begining

It looks as it should per your screenshots, while using a dark gtk theme. while using WhiteSur-light gtk theme, it looks like this.
![image](https://user-images.githubusercontent.com/36916613/127439823-0ecb8098-4119-4ba1-bf24-f52bc1fc0d46.png)

also looks quite sizable in my 1080p laptop, hope it will be configurable later on

**Comment by ErikReider** [comment] 2021-07-29 07:37
Yeah. The plan is to make it more customizable in the future. For the time being you could always edit the CSS file in src if you know your way around CSS :)

**Comment by kushraj** [comment] 2021-07-29 07:58
>  you could always edit the CSS file 

oh, didn't knew about it, since it is using gtk, I thought it could simply pick the variables from current gtk theme.

Also does wlr-layer-shell works here ? notifs are hidden in fullscreen mode

**Comment by ErikReider** [comment] 2021-07-29 08:04
The css file is filled with some defaults. I'll probably somplify the file later.
I'm using layer-shell to position the notifications and the panel but it is using the same layer as waybar and any other bar. If I'd use the top layer, the notifications and the panel would be visible while locked...

**Comment by ErikReider** [comment] 2021-07-29 08:48
This should be fixed in the latest commit 🤞

**Comment by kushraj** [comment] 2021-07-29 09:07
thanks, theming issue is gone now. you might want to look into how dunst handle the fullscreen case. it is able to show notifications in fullscreen mode, yet hidden while locked

**Comment by ErikReider** [comment] 2021-07-29 09:10
@kushraj The issue is that when a notification is visible and you lock, it'll be visible while new notifications aren't visible. Dunst also has this issue

**Closed** 2021-07-29 09:14 UTC
